version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/srtider_server
    networks:
      - strider_network

networks:
  strider_network:
    external: true
